### ISSUE TITLE
Create admin page 

### ISSUE THREAD

**Issue by fpscala** [behruz-b/ubtuit-programmers-board#4]
Administrator sahifasini yaratish!
![image](https://user-images.githubusercontent.com/37735368/72733671-22ade900-3bba-11ea-846e-3c232cf73964.png)
1. `/admin` url orqali sahifaga kirish!
2.

**Comment by ExcuseMeBro** [comment]
/admin url orqali sahifaga kirish! <- This task is complate  (20:41) and admin.scala.html page is created!

**Comment by ExcuseMeBro** [comment]
developmentga push atib qo`ydim!
