### ISSUE TITLE
Create login page 

### ISSUE THREAD

**Issue by fpscala** [behruz-b/ubtuit-programmers-board#5]
![image](https://user-images.githubusercontent.com/37735368/72734302-3d349200-3bbb-11ea-9aee-a6ff4d90bc32.png)
1. Login  sahifasini yaratish!
2. ` /login ` url orqali shu sahifani ochish!
3.  Login tugmasi bosilganda Admin sahifasiga o`tish!

**Comment by ExcuseMeBro** [comment]
1.login pages is ready
2. /register URL use open login page
![Screenshot from 2020-01-20 21-48-24](https://user-images.githubusercontent.com/57610011/72746165-43cf0380-3bd3-11ea-8a30-e08fba6ad315.png)
